In [3]:
# Create a 1D array of numbers from 10 to 50.
import numpy as np
arr_1d=np.arange(10,51)
print(arr_1d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [2]:
# Create a 3x3 array of random numbers between 0 and 1.
arr=np.random.rand(3,3)
print(arr)

[[0.10470419 0.38383428 0.79940291]
 [0.149026   0.59651977 0.5432621 ]
 [0.62290844 0.15096647 0.79436771]]


In [4]:
# Find the shape, size, and data type of the array you created in the previous task.
print("Shape :",arr_1d.shape)
print("Size :",arr_1d.size)
print("Data types :",arr_1d.dtype)

Shape : (41,)
Size : 41
Data types : int64


In [5]:
# Add 5 to every element of a 1D array.
print(arr_1d+5)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [6]:
# Multiply two 2D arrays element-wise.
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
result=np.multiply(array1,array2)
print(result)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [8]:
# Create a 5x5 array of integers from 1 to 25. 
arr_5d=np.arange(1,26).reshape(5,5)
print(arr_5d)
# First Row
print("1st row :",arr_5d[:1])
#Last Column
print("last Column :",arr_5d[:,4:])
# A subarray of the first three rows and first two columns.
copy=arr_5d[:3,:2]
print("Subarray :",copy)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
1st row : [[1 2 3 4 5]]
last Column : [[ 5]
 [10]
 [15]
 [20]
 [25]]
Subarray : [[ 1  2]
 [ 6  7]
 [11 12]]


In [9]:
# Create a 10-element array of random integers between 1 and 100. 
arr=np.random.randint(1,101,size=10)
print(arr)
# The maximum value.
print("Max :",np.max(arr))
print("Min :",np.min(arr))
# The mean and standard deviation.
print("Mean :",np.mean(arr))
print("Standard Deviation :",np.std(arr))

[16 43 90 64 97 68 24 76 60 56]
Max : 97
Min : 16
Mean : 59.4
Standard Deviation : 24.77579463912308


In [10]:
# Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
array=np.arange(1,13)
print(array)
reshaped=array.reshape(3,4)
print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
# Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
print("Matix of ones")
onesarr=np.ones((3,3))
print(onesarr)
print("Updated matrix")
print(onesarr+[1,2,3])

Matix of ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Updated matrix
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [13]:
# Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5
arr=np.random.randint(1,51,size=20)
divisible_by5=arr[arr%5==0]
print("Original array :",arr)
print("Array divisible by 5 :",divisible_by5) 

Original array : [26 28 14 18 16 26 18 28 42 39 50 48 27 23  8 47 46 40 34 41]
Array divisible by 5 : [50 40]


In [15]:
# Create two 2x2 matrices and perform matrix multiplication.
arr1_2d=np.array([[1,2],[3,4]])
arr2_2d=np.array([[5,6],[7,8]])
print("Matrix multiplication :")
print(np.dot(arr1_2d,arr2_2d))

Matrix multiplication :
[[19 22]
 [43 50]]


In [18]:
# Given a 4x4 array, use fancy indexing to extract the diagonal elements.
arr_4d=np.arange(1,17).reshape(4,4)
print("Original matrix :")
print(arr_4d)
diagnol_matrix=arr_4d[np.arange(4),np.arange(4)]
print("Diagnol elements :")
print(diagnol_matrix)

Original matrix :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagnol elements :
[ 1  6 11 16]
